N = int(input('digite um número para ver sua tabuada: '))
print('-' * 12)
print('{} X {:2} = {}'.format(N, 1, N*1))
print('{} X {:2} = {}'.format(N, 2, N*2))
print('{} X {:2} = {}'.format(N, 3, N*3))
print('{} X {:2} = {}'.format(N, 4, N*4))
print('{} x {:2} = {}'.format(N, 5, N*5))
print('{} X {:2} = {}'.format(N, 6, N*6))
print('{} X {:2} = {}'.format(N, 7, N*7))
print('{} X {:2} = {}'.format(N, 8, N*8))
print('{} X {:2} = {}'.format(N, 9, N*9))
print('{} X {:2} = {}'.format(N, 10, N*10))
print('-' * 12)